# 线性代数

In [3]:
 import torch

In [4]:
x= torch.arange(4)
len(x)

4

In [6]:
x[1],x.shape

(tensor(1), torch.Size([4]))

In [7]:
A = torch.arange(20).reshape(5, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [8]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [55]:
B=A.clone() #直接b=a 则是共用一个id
B

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

clone（）法 重新分配地址

计算张量 或 矩阵的 all元素sum

In [11]:
A.sum()

tensor(190)

In [12]:

A_sum_axis0 = A.sum(axis=0)
A,A_sum_axis0

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]]),
 tensor([40, 45, 50, 55]))

# 沿指定的轴降低维度

汇总到0轴  (上下压

In [13]:
A_sum_1 = A.sum(axis=1)
A,A_sum_1

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]]),
 tensor([ 6, 22, 38, 54, 70]))

汇总在1轴

In [18]:
A_sum_11=A.sum(axis=1,keepdim=True)
#维持轴数
A_sum_11

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

In [16]:
 A = A.float()
A.mean() #平均值

tensor(9.5000)

In [19]:
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [56]:
A.cumsum(axis=0) #累加求和

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

理解一下 轴  列↓为axis0  行为1 按轴sum即该轴求和 即压缩轴为点 该轴上的数字（长度失去了 shape[5,4] 则axis 0 1  0对应5  axis0则5失去了  shape为4
shape[2,3,4] axis1 则3失去 [2,4]

In [57]:
d = torch.ones(2,4, 3)
d,d.sum(axis=1),d.sum(axis=0)


(tensor([[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],
 
         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]),
 tensor([[4., 4., 4.],
         [4., 4., 4.]]),
 tensor([[2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.]]))

In [59]:
d,d.sum(axis=1,keepdim=True) #keepdim的话 不是失去而是变为1

(tensor([[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],
 
         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]),
 tensor([[[4., 4., 4.]],
 
         [[4., 4., 4.]]]))

In [60]:
d.sum(axis=[0,1],keepdim=True) #可以同时压缩多个维度

tensor([[[8., 8., 8.]]])

# hadamoard积 数学积

点积 按位乘（Hadamard积

In [25]:
q =torch.ones(4,dtype=torch.float32)
p = torch.tensor([1,2,3,4.0])
torch.dot(q,p)

tensor(10.)

mv 算真真的乘法，常常是矩阵乘向量（列) 注意 矩阵列数==向量维度

In [35]:
A.shape, p.shape, torch.mv(A, p)

(torch.Size([5, 4]), torch.Size([4]), tensor([ 20.,  60., 100., 140., 180.]))

mm 数学的矩阵乘法  （同理 注意维度 sk:顶真）

In [42]:
B = torch.ones(4, 3)
torch.mm(A, B)


tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

In [44]:
c=torch.ones(2,3,4)
len(c) #see len 

2

# 向量长度 范数 norm

L2 范数 欧几里得距离

In [38]:
p, torch.norm(p)

(tensor([1., 2., 3., 4.]), tensor(5.4772))

L1 范数 曼哈顿距离  

In [39]:
torch.abs(p).sum()

tensor(10.)

Lp 范数 则是更通用的式子

# 矩阵Frobenius范数 同L2

In [40]:
torch.norm(torch.ones((4, 9)))

tensor(6.)

# 范数的重要性--目标被表示为范数

 用向量表示物品
 最小化相似项目之间的距离，最大化不同项目之间的距离。
 

# 矩阵求导？