# 数据操作

获取 储存数据
数据结构：pytorch tensor（张量 n维数组） (numpy中有ndarray 但只能用cpu 且不能自动微分 so 我们用tensor）



In [57]:
import torch

# 创建张量
几个[[ 就是几维度

.arange 自然数

In [58]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [59]:
x.shape #访问形状

torch.Size([12])

In [60]:
x.numel()#种数


12

In [61]:
x = x.reshape(2,-1)#用-1占位  自动计算需要2行的列数
x

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])

In [62]:
x = x.reshape(3,4)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [63]:
.tensor 自定义

SyntaxError: invalid syntax (4040446139.py, line 1)

In [64]:
y=torch.tensor([1,1,1,1,2,2,2,2,3,3,3,3])
y = y.reshape(3,4)


.ones .zeros 全01

In [65]:
torch.ones(1,2)

tensor([[1., 1.]])

In [66]:
torch.zeros(2,3,4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

.randn 随机

# 运算

In [67]:
x == y

tensor([[False,  True, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [68]:
x.sum()

tensor(66)

按位相乘（不同于数学）

In [69]:
x * y


tensor([[ 0,  1,  2,  3],
        [ 8, 10, 12, 14],
        [24, 27, 30, 33]])

幂运算

In [70]:
x ** y

tensor([[   0,    1,    2,    3],
        [  16,   25,   36,   49],
        [ 512,  729, 1000, 1331]])

结合两个张量

In [71]:
torch.cat((x,y),dim=0)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [ 1,  1,  1,  1],
        [ 2,  2,  2,  2],
        [ 3,  3,  3,  3]])

In [72]:
torch.cat((x,y),dim=1)

tensor([[ 0,  1,  2,  3,  1,  1,  1,  1],
        [ 4,  5,  6,  7,  2,  2,  2,  2],
        [ 8,  9, 10, 11,  3,  3,  3,  3]])

指定dim =0只是上下累积，=1则在一个维度中链接

# 广播机制broadcasting mechanism 
自动通过复制补充填满为相同shape的张量 再进行加减

In [73]:
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [74]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

# 元素访问

In [75]:
x[-1],x[1:3]

(tensor([ 8,  9, 10, 11]),
 tensor([[ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]))

In [76]:
x=x.reshape((3,4))

In [77]:
x[0:2,:] = 12
x

tensor([[12, 12, 12, 12],
        [12, 12, 12, 12],
        [ 8,  9, 10, 11]])

选中0到2 前闭后开 冒号表示该行全选

# 原地操作 避免浪费内存

In [78]:
z = torch.zeros_like(x)
print('id:',id(z))
z[:] = x + x
print('id',id(z))

id: 2203268867152
id 2203268867152


id为类似指针的东西
用冒号全选中

# tensor可转换为其他对象


In [79]:
m = x.numpy() #转为numpy的dnarray
b =torch.tensor(m) # 同自定义法 直接创建

type(m),type(b)

(numpy.ndarray, torch.Tensor)

# 数据预处理
use pandas 将原始数据 转为tensor格式 

# 创建数据集 存csv文件中
逗号分隔值文件 一行为表头列名 下面都是表中的数据）

In [80]:
import os

os.makedirs(os.path.join('..','data'),exist_ok=True)
data_file = os.path.join('..','data','house_tiny.csv')
with open(data_file,'w') as f:
    f.write('Numrooom,alley,price\n')#列名
    f.write('na,na,104000\n')
    f.write('pace,na,106000\n')
    

os 是 Python 标准库中的一个模块，提供了丰富的功能用于与操作系统进行交互
这个模块允许你执行很多与操作系统相关的任务，例如文件和目录的操作、进程管理、环境变量获取等。（获取当前工作目录cwd = os.getcwd()）
os.makedirs 函数创建一个新的目录
os.path.join('..', 'data') 表示在当前目录的上一级目录中创建一个名为 data 的目录
exist_ok=True 表示如果目录已经存在，不会报错
定义 CSV 文件的路径 data_file，将其设定为上一级目录中的 data 目录下的 house_tiny.csv 文件
这段代码打开（如果文件不存在则创建）一个名为 house_tiny.csv 的文件，模式为写入（'w'），并将文件对象赋值给 f。然后使用 f.write 方法向文件中写入数据

用panda pd. 读取文件

In [81]:
import pandas as pd

data = pd.read_csv(data_file)
data

Numrooom alley   price
0       na    na  104000
1     pace    na  106000

# 处理缺失数据（NaN）  常选插值方法

In [82]:
inputs,output = data.iloc[:,0:2],data.iloc[:,2] #iloc方法选择索引
inputs = inputs.fillna(inputs.mean()) 
print(inputs)

  Numrooom alley
0       na    na
1     pace    na


inputs.fillna(inputs.mean()) 将 inputs DataFrame 中的缺失值（NaN）用 inputs 每一列的均值替换。

In [83]:
inputs = pd.get_dummies(inputs,dummy_na=True)
print(inputs)

   Numrooom_na  Numrooom_pace  Numrooom_nan  alley_na  alley_nan
0            1              0             0         1          0
1            0              1             0         1          0


用dummies 讲inputs数据变为离散型01

# 数据全为数值时 转为tensor

In [84]:
x = torch.tensor(inputs.values)
x

tensor([[1, 0, 0, 1, 0],
        [0, 1, 0, 1, 0]], dtype=torch.uint8)